target:
    service: sing
    name: msrresrchvc
    # workspace_name: <workspace_name>  # optional if the target already has an associated default workspace

environment:
  image: amlt-sing/pytorch-1.8.0 #teslazhu/torchgm:latest
  setup:
  - pip install torch-scatter -f https://data.pyg.org/whl/torch-1.8.0+cu111.html
  - pip install torch-sparse==0.6.12 -f https://data.pyg.org/whl/torch-1.8.0+cu111.html
  - pip install torch-geometric==2.0.3
  - pip install ogb
  - pip install azureml-sdk
  image_setup:
  - conda install -c conda-forge rdkit -y

code:
  local_dir: code

data:
  local_dir: data
  remote_dir: shufxi/amltdata/retroring

jobs:
- name: eval_1
  sku: G1-P40-P100
  command:
  - >-
    python test.py
    --test-ckpt $${AMLT_MAP_INPUT_DIR}/checkpoint_56.pt
    --batch-size 64 --dropout 0.3 --encoder-dropout 0.1
    --pooler-dropout 0.1 --init-face --use-bn
    --num-layers 6
    --mlp-hidden-size 256 --node-attn
    --result-path $${AMLT_OUTPUT_DIR}/test_output.txt
    --raw-data-path $${AMLT_DATA_DIR}/data/uspto50k
  - >- 
    python decode.py
    -d $${AMLT_DATA_DIR}/data/uspto50k
    -k 50
    -p $${AMLT_OUTPUT_DIR}/test_output.txt
    -o $${AMLT_OUTPUT_DIR}/decode_output.txt
  - >-
    python top_k_acc.py
    --data $${AMLT_DATA_DIR}/data/uspto50k
    --result-file $${AMLT_OUTPUT_DIR}/decode_output.txt
    | tee $${AMLT_OUTPUT_DIR}/acc.txt
  submit_args:
      env:
        { AMLT_DOCKERFILE_TEMPLATE: default, AMLT_NO_TENSORBOARD_PATCHING: 1 }
- name: eval_2
  sku: G1-P40-P100
  command:
  - >-
    python test.py
    --test-ckpt $${AMLT_MAP_INPUT_DIR}/checkpoint_34.pt
    --batch-size 64 --dropout 0.3 --encoder-dropout 0.1
    --pooler-dropout 0.2 --init-face --use-bn
    --num-layers 6
    --mlp-hidden-size 1024 --latent-size 512 --node-attn
    --result-path $${AMLT_OUTPUT_DIR}/test_output.txt
    --raw-data-path $${AMLT_DATA_DIR}/data/uspto50k
  - >- 
    python decode.py
    -d $${AMLT_DATA_DIR}/data/uspto50k
    -k 50
    -p $${AMLT_OUTPUT_DIR}/test_output.txt
    -o $${AMLT_OUTPUT_DIR}/decode_output.txt
  - >-
    python top_k_acc.py
    --data $${AMLT_DATA_DIR}/data/uspto50k
    --result-file $${AMLT_OUTPUT_DIR}/decode_output.txt
    | tee $${AMLT_OUTPUT_DIR}/acc.txt
  submit_args:
      env:
        { AMLT_DOCKERFILE_TEMPLATE: default, AMLT_NO_TENSORBOARD_PATCHING: 1 }
- name: eval_2.logit
  sku: G1-P40-P100
  command:
  - >-
    python test.py
    --test-ckpt $${AMLT_MAP_INPUT_DIR}/checkpoint_34.pt
    --batch-size 64 --dropout 0.3 --encoder-dropout 0.1
    --pooler-dropout 0.2 --init-face --use-bn
    --num-layers 6
    --mlp-hidden-size 1024 --latent-size 512 --node-attn
    --result-path $${AMLT_OUTPUT_DIR}/test_output.txt
    --raw-data-path $${AMLT_DATA_DIR}/data/uspto50k
    --rank-logit
  - >- 
    python decode.py
    -d $${AMLT_DATA_DIR}/data/uspto50k
    -k 50
    -p $${AMLT_OUTPUT_DIR}/test_output.txt
    -o $${AMLT_OUTPUT_DIR}/decode_output.txt
  - >-
    python top_k_acc.py
    --data $${AMLT_DATA_DIR}/data/uspto50k
    --result-file $${AMLT_OUTPUT_DIR}/decode_output.txt
    | tee $${AMLT_OUTPUT_DIR}/acc.txt
  submit_args:
      env:
        { AMLT_DOCKERFILE_TEMPLATE: default, AMLT_NO_TENSORBOARD_PATCHING: 1 }
- name: eval_3
  sku: G1-P40-P100
  command:
  - >-
    python test.py
    --test-ckpt $${AMLT_MAP_INPUT_DIR}/checkpoint_best.pt
    --batch-size 64 --dropout 0.4 --encoder-dropout 0.1
    --pooler-dropout 0.1 --init-face --use-bn
    --num-layers 6
    --mlp-hidden-size 768 --latent-size 512 --node-attn
    --result-path $${AMLT_OUTPUT_DIR}/test_output.txt
    --raw-data-path $${AMLT_DATA_DIR}/data/uspto50k
  - >- 
    python decode.py
    -d $${AMLT_DATA_DIR}/data/uspto50k
    -k 50
    -p $${AMLT_OUTPUT_DIR}/test_output.txt
    -o $${AMLT_OUTPUT_DIR}/decode_output.txt
  - >-
    python top_k_acc.py
    --data $${AMLT_DATA_DIR}/data/uspto50k
    --result-file $${AMLT_OUTPUT_DIR}/decode_output.txt
    | tee $${AMLT_OUTPUT_DIR}/acc.txt
  submit_args:
      env:
        { AMLT_DOCKERFILE_TEMPLATE: default, AMLT_NO_TENSORBOARD_PATCHING: 1 }
- name: eval_4
  sku: G1-P40-P100
  command:
  - >-
    python test.py
    --test-ckpt $${AMLT_MAP_INPUT_DIR}/checkpoint_best.pt
    --batch-size 64 --dropout 0.3 --encoder-dropout 0.1
    --pooler-dropout 0.1 --init-face --use-bn
    --num-layers 6
    --mlp-hidden-size 1024 --latent-size 512 --node-attn
    --result-path $${AMLT_OUTPUT_DIR}/test_output.txt
    --raw-data-path $${AMLT_DATA_DIR}/data/uspto50k
  - >- 
    python decode.py
    -d $${AMLT_DATA_DIR}/data/uspto50k
    -k 50
    -p $${AMLT_OUTPUT_DIR}/test_output.txt
    -o $${AMLT_OUTPUT_DIR}/decode_output.txt
  - >-
    python top_k_acc.py
    --data $${AMLT_DATA_DIR}/data/uspto50k
    --result-file $${AMLT_OUTPUT_DIR}/decode_output.txt
    | tee $${AMLT_OUTPUT_DIR}/acc.txt
  submit_args:
      env:
        { AMLT_DOCKERFILE_TEMPLATE: default, AMLT_NO_TENSORBOARD_PATCHING: 1 }
- name: eval_5
  sku: G1-P40-P100
  command:
  - >-
    python test.py
    --test-ckpt $${AMLT_MAP_INPUT_DIR}/checkpoint_best.pt
    --batch-size 64 --dropout 0.4 --encoder-dropout 0.1
    --pooler-dropout 0.1 --init-face --use-bn
    --num-layers 6
    --mlp-hidden-size 768 --latent-size 512 --node-attn
    --result-path $${AMLT_OUTPUT_DIR}/test_output.txt
    --raw-data-path $${AMLT_DATA_DIR}/data/uspto50k
  - >- 
    python decode.py
    -d $${AMLT_DATA_DIR}/data/uspto50k
    -k 50
    -p $${AMLT_OUTPUT_DIR}/test_output.txt
    -o $${AMLT_OUTPUT_DIR}/decode_output.txt
  - >-
    python top_k_acc.py
    --data $${AMLT_DATA_DIR}/data/uspto50k
    --result-file $${AMLT_OUTPUT_DIR}/decode_output.txt
    | tee $${AMLT_OUTPUT_DIR}/acc.txt
  submit_args:
      env:
        { AMLT_DOCKERFILE_TEMPLATE: default, AMLT_NO_TENSORBOARD_PATCHING: 1 }