target:
    service: sing
    name: msrresrchvc
    # workspace_name: <workspace_name>  # optional if the target already has an associated default workspace

environment:
  image: amlt-sing/pytorch-1.8.0 #teslazhu/torchgm:latest
  setup:
  - pip install torch-scatter -f https://data.pyg.org/whl/torch-1.8.0+cu111.html
  - pip install torch-sparse==0.6.12 -f https://data.pyg.org/whl/torch-1.8.0+cu111.html
  - pip install torch-geometric==2.0.3
  - pip install ogb
  - pip install azureml-sdk
  image_setup:
  - conda install -c conda-forge rdkit -y

code:
  local_dir: code

data:
  local_dir: data
  remote_dir: shufxi/amltdata/retroring

search:
  job_template:
    name: train_uspto50k_gra_bsz{bsz}_drop{dropout}_pdrop{poolerdropout}_lr{lr}_wd{wd}_l{layers}_mlp{mlp}_latent{latent}
    sku: G1-P40-P100
    command:
    - nvidia-smi
    - python -c "import torch; print('torch', torch.__version__)"
    - python -c "import torch; print('cuda', torch.version.cuda)"
    - python -c "import torch_geometric;print('pyg', torch_geometric.__version__)"
    - python -c "import ogb; print('ogb', ogb.__version__)"
    - >-
      python -u train.py
      --batch-size {bsz} --dropout {dropout} --encoder-dropout 0.1
      --pooler-dropout {poolerdropout} --init-face --use-bn --epochs 100
      --num-layers {layers} --lr {lr} --weight-decay {wd}  --beta2 0.999 
      --mlp-hidden-size {mlp} --latent-size {latent} --lr-warmup --use-adamw --node-attn --gradmultiply -1
      --gra-layers 1
      --seed 46
      --save-ckt
      --log-interval 10
      --checkpoint-dir $${AMLT_OUTPUT_DIR}
      --raw-data-path $${AMLT_DATA_DIR}/data/uspto50k
    submit_args:
      env:
        { AMLT_DOCKERFILE_TEMPLATE: default, AMLT_NO_TENSORBOARD_PATCHING: 1 }
  type: grid
  max_trials: 1000
  params:
    - name: bsz
      spec: discrete
      values: [64]
    - name: dropout
      spec: discrete
      values: [0.3, 0.4]
    - name: poolerdropout
      spec: discrete
      values: [0.1, 0.2]
    - name: lr
      spec: discrete
      values: [0.0001, 0.0002]
    - name: wd
      spec: discrete
      values:  [0.1]
    - name: layers
      spec: discrete
      values: [3, 6]
    - name: mlp
      spec: discrete
      values: [512, 768, 1024]
    - name: latent
      spec: discrete
      values: [512]